### ISSUE TITLE
Decide on Tier Definitions

### ISSUE THREAD

**Issue by Mako88** [KOTORCommunityPatches/K1_Community_Patch#39]
Before we can move forward with the 1.8 release we need to definitively decide on the definitions of the three tiers.

I propose the following:

Note: selecting any tier automatically installs all fixes in the tiers below it

Tier 1 - Non-Visual Fixes. These are fixes that don't make any visual changes
Tier 2 - Visual Fixes and Enhancements. These are fixes that are visually noticeable, as well as things that aren't technically fixes, but make sense given the context, lore, etc.
Tier 3 - Suggestions. These are things that are quite obviously departures from the base game, but the three of us feel should have been part of the base game (or we feel that any modern player would appreciate. The lite upgrade stuff is an example of this).

Optionally we could have an "incompatible stuff" mini-tier. It would include anything that would normally fall under Tier 1 or Tier 2, but that has the potential to break other mods. This would be separately-selectable item in the installer and would not be installed when just selecting Tier 1 or Tier 2. However anything that's a part of this tier would be included in Tier 3 (so that people can still have a one-click-installs-everything experience).

**Comment by JCarter426** [comment]
The tier definitions still seem nebulous to me, so I've tried grouping every fix by what they actually do, without regard for the tier they belong in. I'm hoping that'll make it easier to assign them to tiers later, because it should be an all or nothing deal - the whole group goes into whatever tier.

If I've set things up right, everybody should have permisison to reorder these lists. So feel free to do that.

## Bug Fixes
These are the most critical fixes. If a bug is on this list, it isn't just a minor annoyance, but actually prevents you from playing the game the way it was meant to be played - restricting access to content, making it impossible to complete quests, and so on.
- [x] A line in k_hjuh_dialog.dlg was inaccessible: [KOTOR Bug Fix Attempt 1.1](http://deadlystream.com/forum/files/file/470-kotor-bug-fix-attempt/)
- [x] Bacca's Blade Hilt script would sometimes not allow you to receive it: [The Comprehensive KOTOR Bug Fix Collection](https://www.nexusmods.com/kotor/mods/75)
- [x] Carth was a little too quick to complain about being out of the loop [ISSUE #2](https://github.com/KOTORCommunityPatches/K1_Community_Patch/issues/2)
- [x] Canderous's personal quest is bugged
- [x] Dak was a little too fond of the Dreshdae cantina [ISSUE #7](https://github.com/KOTORCommunityPatches/K1_Community_Patch/issues/7)
- [x] Griff sometimes wouldn't spawn in the Sand People Enclave
- [x] If doing Juhani’s dialog in the wrong order, it was possible to block any further progress
- [x] If you force persuaded Ignus, he wouldn't testify on your behalf: [The Comprehensive KOTOR Bug Fix Collection](https://www.nexusmods.com/kotor/mods/75)
- [x] If you've talked with Bastila after kissing her, some dialog isn't available on the Rakatan Temple: [Bastila Romance Scriptfix 1.0](http://deadlystream.com/forum/files/file/1086-bastila-romance-scriptfix/)
- [x] It's possible to get infinite LS points in a conversation loop with Worronzor
- [x] Juhani wouldn't spawn in the post-Leviathan scene (Fix found by Kexikus, implemented by AFP)
- [x] On board the Yavin Station, when the Trandoshans appear for the first time, some of the dialog options sometimes causes you to be kicked out of the dialog: [The Comprehensive KOTOR Bug Fix Collection](https://www.nexusmods.com/kotor/mods/75)
- [x] On the Star Forge if you haven't talked to Bastila after kissing her, some dialog isn't available: [Bastila Romance Scriptfix 1.0](http://deadlystream.com/forum/files/file/1086-bastila-romance-scriptfix/)
- [x] On the Star Forge, if you have denied the romance, the game acts as if you haven't: [Bastila Romance Scriptfix 1.0](http://deadlystream.com/forum/files/file/1086-bastila-romance-scriptfix/)
- [x] Once Xor appeared, no other messengers could appear: [The Comprehensive KOTOR Bug Fix Collection](https://www.nexusmods.com/kotor/mods/75)
- [x] One of the boxes in the Rakatan Temple is inaccessible
- [x] Party members in stealth during the post-Leviathan scene were game breaking (workaround/partial fix) [ISSUE #9](https://github.com/KOTORCommunityPatches/K1_Community_Patch/issues/9)
- [x] Respawn tach gland in chest on Kashyyk if player has received quest from Griff
- [x] Sand People disguises would misbehave if the player used the rapid transit system or loaded from a save while disguised
- [x] Some DS responses were unavailable in k_hcar_dialog.dlg: [KOTOR Bug Fix Attempt 1.1](http://deadlystream.com/forum/files/file/470-kotor-bug-fix-attempt/)
- [x] Some of Bastila's lines regarding her father's holocron were unavailable: [KOTOR Bug Fix Attempt 1.1](http://deadlystream.com/forum/files/file/470-kotor-bug-fix-attempt/)
- [x] Sometimes the wrong dialog would play during the Leviathan torture scene: [The Comprehensive KOTOR Bug Fix Collection](https://www.nexusmods.com/kotor/mods/75)
- [x] Tanis' dialogue on Tatooine was bugged when playing as a female: [The Comprehensive KOTOR Bug Fix Collection](https://www.nexusmods.com/kotor/mods/75)
- [x] The Iridorian's dialog script would stop you in the middle of the dialog choice: [The Comprehensive KOTOR Bug Fix Collection](https://www.nexusmods.com/kotor/mods/75)
- [x] The second Xor encounter is unavailable on Tatooine
- [x] The second Xor encounter was impossible to start if you first meet him and his goons without Juhani in the party
- [x] The XP reward for delivering the box to Motta the Hutt was incorrect: [The Comprehensive KOTOR Bug Fix Collection](https://www.nexusmods.com/kotor/mods/75)
- [x] There is an inaccessible container in The One's compound
- [x] Various fixes on Korriban: [JC's Korriban: Back in Black for K1](https://deadlystream.com/files/file/1293-jcs-korriban-back-in-black-for-k1/)
- [x] Xor refused to show up for the second encounter unless the player used the rapid transit system [ISSUE #29](https://github.com/KOTORCommunityPatches/K1_Community_Patch/issues/29)
- [x] The Dead Settler quest had several bugs and it was possible to miss out on some items depending on if and when it was triggered

## Developer Oversight
These are fixes for other issues that were likely unintended. They don't break the game, but they are obvious things to fix. These are probably all Tier 1 anyway, but JC was feeling pedantic.
- [x] A droid in the Taris sewers had a vocabulator fault (Reported by ebmar) [ISSUE #15](https://github.com/KOTORCommunityPatches/K1_Community_Patch/issues/15)
- [x] A Sith NPC in the background of a Leviathan bridge cutscene had poor weapon discipline (Reported by ebmar)
- [x] A Sith NPC in the background of a Leviathan bridge cutscene was having a bad hair day (Reported by ebmar)
- [x] A stray blaster appears in the middle of a hallway in the Sith Base on Taris
- [x] Bacca's Blade Hilt was never removed from your inventory: [The Comprehensive KOTOR Bug Fix Collection](https://www.nexusmods.com/kotor/mods/75)
- [x] Bastila and Carth were positioned wrong after the Revelation cutscene: [KOTOR Bug Fix Attempt 1.1](http://deadlystream.com/forum/files/file/470-kotor-bug-fix-attempt/)
- [x] Bastila would not show you the fourth vision if you travelled to all four planets before the Leviathan [K1R](https://deadlystream.com/files/file/558-kotor-1-restoration/) [ISSUE #10](https://github.com/KOTORCommunityPatches/K1_Community_Patch/issues/10)
- [x] Bastilla turned off her lightsaber after the Revelation cutscene: [KOTOR Bug Fix Attempt 1.1](http://deadlystream.com/forum/files/file/470-kotor-bug-fix-attempt/)
- [x] Belaya attacks with her fists (Reported by Mr Ardvark)
- [x] Calo Nord’s soundset was broken: [KOTOR Bug Fix Attempt 1.1](http://deadlystream.com/forum/files/file/470-kotor-bug-fix-attempt/)
- [x] Calo's Rodian prey in the Undercity Apartments didn't draw their blasters (Reported by ebmar)
- [x] Desert wraids and shyraks use wrong texture: [Desert Wraid & Shyrack Texture Fix](http://deadlystream.com/forum/files/file/323-desert-wraid-shyrack-texture-fix/)
- [x] Droid classes’ feat gain was reversed: [Droid Feat Gain Fix 1.0](https://deadlystream.com/files/file/865-kotor-droid-feat-gain-fix/)
- [x] Elora confesses to Sunry's infidelity automatically if you have Jolee or Bastila in your party: [The Comprehensive KOTOR Bug Fix Collection](https://www.nexusmods.com/kotor/mods/75)
- [x] Energy shields don't block electricity: [Energy Shield Damage Fix](http://deadlystream.com/forum/files/file/548-energy-shield-damage-fix/)
- [x] First lightsaber crystal uses wrong icon: [First Lightsaber Crystal Fix 1.0](http://deadlystream.com/forum/files/file/898-first-lightsaber-crystal-fix/)
- [x] Focus and proficiency feat icons are switched: [[KotOR] Fixed Proficiency/Focus Feat Icons 1.0](http://deadlystream.com/forum/files/file/421-kotor-fixed-proficiencyfocus-feat-icons/)
- [x] Gana Lavin's appearance changes and her text dialog doesn't appear
- [x] If the prisoner in the Sith Academy was interrogated multiple times rapidly, the animation would loop for a long time: [The Comprehensive KOTOR Bug Fix Collection](https://www.nexusmods.com/kotor/mods/75)
- [x] It was possible to miss out on HK’s backstory and leave his whole storyline hanging [ISSUE #3](https://github.com/KOTORCommunityPatches/K1_Community_Patch/issues/3)
- [x] Malak's grunt sound didn't play in the Revelation cutscene: [KOTOR Bug Fix Attempt 1.1](http://deadlystream.com/forum/files/file/470-kotor-bug-fix-attempt/)
- [x] Mission has no clothing on when you meet Griff at the spaceport without her in your party
- [x] Multiple fixes for the Endar Spire level models: [Endar Spire Hull Repairs 1.4](https://deadlystream.com/files/file/1357-endar-spire-hull-repairs)
- [x] On the Star Forge, the wrong speaker said the "You are wasting your time..." line: [KOTOR Bug Fix Attempt 1.1](http://deadlystream.com/forum/files/file/470-kotor-bug-fix-attempt/)
- [x] One of Canderous' goons in the Undercity had the wrong soundset (Reported by ebmar)
- [x] Several camera angles on the Star Forge were inconsistent:  [KOTOR Bug Fix Attempt 1.1](http://deadlystream.com/forum/files/file/470-kotor-bug-fix-attempt/)
- [x] Several droids in Davik's Estate have the wrong sound set
- [x] Several textures were missing shader data: [JC's Minor Fixes for K1 1.0](https://deadlystream.com/files/file/1333-jcs-minor-fixes-for-k1/)
- [x] Sith Apprentices have their soundsets mismatched: [The Comprehensive KOTOR Bug Fix Collection](https://www.nexusmods.com/kotor/mods/75)
- [x] Sith fighter laser were the wrong color: [JC's Minor Fixes for K1 1.0](https://deadlystream.com/files/file/1333-jcs-minor-fixes-for-k1/)
- [x] Some camera angles were wrong during the Leviathan interrogation: [KOTOR Bug Fix Attempt 1.1](http://deadlystream.com/forum/files/file/470-kotor-bug-fix-attempt/)
- [x] Some eager Jedi show up a bit too early for their scripted fight on the Star Forge [ISSUE #5](https://github.com/KOTORCommunityPatches/K1_Community_Patch/issues/5)
- [x] Some NPCs have wrong or missing sounds in their soundsets
- [x] Some stunt modules were missing geometry: [JC's Minor Fixes for K1 1.0](https://deadlystream.com/files/file/1333-jcs-minor-fixes-for-k1/)
- [x] The exit in the Sith Base on Taris was labelled incorrectly (Reported by 134340Goat)
- [x] The pause animation on the Star Forge when confronting Bastila had the wrong participant: [KOTOR Bug Fix Attempt 1.1](http://deadlystream.com/forum/files/file/470-kotor-bug-fix-attempt/)
- [x] The player would suffer stage fright right before racing for the Hidden Beks [ISSUE #12](https://github.com/KOTORCommunityPatches/K1_Community_Patch/issues/12)
- [x] Two female Jedi in the Dantooine enclave stop walking after being talked to (Reported by ebmar) [ISSUE #31](https://github.com/KOTORCommunityPatches/K1_Community_Patch/issues/31)
- [x] Two Sith archaeologists are female instead of male: [Male Sith Archaeologist Restoration 1.0](http://deadlystream.com/forum/files/file/1204-male-sith-archaeologist-restoration/)
- [x] Two Sith are standing too close in the Taris destruction sequence: [Taris Escape Sequence Adjustments 1.1](http://deadlystream.com/forum/files/file/1192-taris-escape-sequence-adjustments/)
- [x] Two Twi'lek Czerka Liaison Officers on Kashyyyk didn't respond well to interruption (Reported by Salk) [ISSUE #23](https://github.com/KOTORCommunityPatches/K1_Community_Patch/issues/23)
- [x] Your party can be seen in the background of the Taris destruction sequence: [Taris Escape Sequence Adjustments 1.1](http://deadlystream.com/forum/files/file/1192-taris-escape-sequence-adjustments/)
- [x] Yuthura only attacks with one of her lightsabers
- [x] Several quests aren't properly ended if you are banned from Manaan: [Proper Manaan Quest Endings 1.0](http://deadlystream.com/forum/files/file/557-proper-manaan-quest-endings/)
- [x] The end credits don't scale to screen resolution during the Dark Side ending

## Atmospheric/Lore/Logical Changes
These things aren't exactly problems, and perhaps go beyond developer intent, but they still bothered people. Basically player/modder interpretation of how things should have been.
- [x] Calo Nord has different inventories and stats on different planets
- [x] Czerka employees on Korriban wear Sith uniforms (Reported by Mr Ardvark)
- [x] Dune sea miners on Tatooine aren't wearing Czerka gear (Reported by Mr Ardvark)
- [x] Handon on Dantooine didn't look injured like he was supposed to be: [Handon's Enhanced Waistline](https://deadlystream.com/files/file/1367-tor-ports-handons-enhanced-waistline/) (Scripts only)
- [x] Helena wears Jedi robes instead of regular clothes
- [x] Infected Republic Soldier on Taris wears a combat suit (Reported by Mr Ardvark)
- [x] Kandon Ark doesn't wear his military suit: [Kandon Ark Fix 1.0](http://deadlystream.com/forum/files/file/1026-kandon-ark-fix/)
- [x] Many Sith Troopers or Officers had the wrong appearance
- [x] Queedle is the wrong race considering several different pieces of dialog: [Queedle Fix 1.0](https://deadlystream.com/files/file/1267-queedle-fix/)
- [x] Red lightsaber crystal uses wrong icon:  [Red Lightsaber Crystal Fix 1.0](http://deadlystream.com/forum/files/file/911-red-lightsaber-crystal-fix/)
- [x] Removed Dark Jedi Corpse from Hrakert Rift Station, and moved his inventory to a chest in the Sith Embassy (Reported by Mr Ardvark)
- [x] Sapith crystal uses wrong icon: [Sapith Fix 1.0](http://deadlystream.com/forum/files/file/975-sapith-fix/)
- [x] Shaardan attacks with a sword (Reported by Mr Ardvark)
- [x] The appearance of Casus’ body didn’t suit him or the conditions of his death (suggested by DarthParametric)
- [x] The corpse in the Dantooine Murder Mystery looked a bit crusty for such a fresh kill (Suggested by A Future Pilot)
- [x] Xor is non-human, while he was human in the XBox version: [Human Xor Restoration 1.0](http://deadlystream.com/forum/files/file/1091-human-xor-restoration/)
- [x] Carth is now an equal opportunity complainer when it comes to exploding swoop bikes

## Annoyance Fixes
These things annoyed players.
- [x] The security camera dialog on Manaan was extremely annoying: [JC's Minor Fixes for K1 1.0](https://deadlystream.com/files/file/1333-jcs-minor-fixes-for-k1/)
- [ ] Faster Scuba

## Visual Improvements
Sometimes the game assets are just bad. These correct problems with them, and may require modder-created assets. But the changes are minimal; they just make the game look how it ought to look.
- [x] The collars on female Class 7 (PFBF) and Class 9 (PFBH) armours clip into some heads: [Female Armour Collar Fix 1.0](https://deadlystream.com/files/file/1425-female-armour-collar-fix)
- [x] The commoner Asian male head comm_a_m had incorrectly named eye trimeshes
- [x] The Council on Dantooine float a few inches off the ground
- [x] The Ebon Hawk has several holes in its models: [Ebon Hawk K1 Fixes 2.0](http://deadlystream.com/forum/files/file/1134-ebon-hawk-k1-fixes/)
- [x] The Ebon Hawk model in the Leviathan hangar was missing landing gear and access ramp [ISSUE #30](https://github.com/KOTORCommunityPatches/K1_Community_Patch/issues/30)
- [x] The hanging ivy on the walls of the Dantooine enclave landing pad has a couple of positional issues
- [x] The male player head PMHC01 has some deformation issues along the jawline
- [x] The training montage on Dantooine had a number of minor issues [ISSUE #16](https://github.com/KOTORCommunityPatches/K1_Community_Patch/issues/16)
- [x] There are missing lightmaps in the entrance of the Taris Upper City cantina: [Taris Upper City Cantina Entrance Wall Panel Fix 1.0](https://deadlystream.com/files/file/1345-taris-upper-city-cantina-entrance-wall-panel-fix)
- [x] Higher poly replacements for the placeable human "sitters" (cantina Pazaak players/drinkers)
- [x] Many background NPCs use "lite" models [K1 Lite Upgrader 1.3](https://deadlystream.com/files/file/1291-k1-lite-upgrader/)
- [x] The walking animation doesn't look good: [Movement Animation Fix for both KOTOR and TSL](http://deadlystream.com/forum/files/file/465-movement-animation-fix-for-both-kotor-and-tsl/)
- [ ] Republic Soldier Fixes

## Ported Content
Everything here involves content ported from another game.
- [x] Some poor quality commoner clothes textures were replaced with improved versions ported from TSL [ISSUE #32](https://github.com/KOTORCommunityPatches/K1_Community_Patch/issues/32)
- [x] Trandoshans lack a functioning soundset. New one created from sounds ported from TSL.
- [ ] Dense Aliens

## And the Rest
Everything here has been included in or nominated for the Community Patch at some point, but there isn't 100% consensus for it. There might've been some specific objection to the content, or a compatibility concern. Or we just don't know where to put it yet.
- [x] Mandalorian armor has several issues: [Mandalorian Armor Fixes](https://www.nexusmods.com/kotor/mods/1174)
- [x] Some non-dancer Twi'lek female NPCs wear armour instead of commoner clothes [ISSUE #14](https://github.com/KOTORCommunityPatches/K1_Community_Patch/issues/14)
- [x] The door on the Star Forge that closes the PC in with the droids was bashable: [Star Forge Door Fix 1.50](https://deadlystream.com/files/file/1195-star-forge-door-fix/)
- [x] Vrook and Zhar wear the wrong color robes: [Vrook and Zhar Fix 1.0](http://deadlystream.com/forum/files/file/896-vrook-and-zhar-fix/)
- [ ] Sith Soldier Texture Restoration

**Comment by Mako88** [comment]
I think Bug Fixes and Developer Oversights should be Tier 1. Atmospheric/Lore/Logical Changes should be Tier 2, and everything else should be Tier 3.

Alternatively Developer Oversights could be moved to Tier 2.

I do like having the headings that you've created though as a guideline for what goes in which Tier. (Basically we categorize which heading a particular change goes under, and then put the headings into the tiers as I recommended [pending any differences of opinion]).

**Comment by Mako88** [comment]
I re-categorized "And the Rest" based on my opinions

**Comment by JCarter426** [comment]
After investigating the Mandalorian armor stuff, I've moved it over to Visual Improvements as it requires new assets. I'm also going to redo it for the Community Patch as I'm not entirely satisfied with the source mod, primarily the removal of the disguise effect for the Mandalorian Assault Armor.

**Comment by Mako88** [comment]
I'd be OK with annoyance fixes being Tier 2. When testing, I would like to make sure of one thing with the faster scuba implementation though: I remember when developing it you would just accelerate indefinitely. I'm 99% sure I fixed that, but I'd want to double-check before putting into the patch.

**Comment by JCarter426** [comment]
Since we seem to have a consensus, I've transferred the new organization over (https://github.com/KOTORCommunityPatches/K1_Community_Patch/blob/master/Tier%20Organization.md)[here].
